/**:
  ros__parameters:
    use_sim_time: true

controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    antobot_robot:
      type: diff_drive_controller/DiffDriveController

antobot_robot:
  ros__parameters:
    left_wheel_names: ["wheel_left_front_joint", "wheel_left_rear_joint"]
    right_wheel_names: ["wheel_right_front_joint", "wheel_right_rear_joint"]
    wheel_separation: 0.52
    wheel_radius: 0.15
    publish_rate: 50
    cmd_vel_timeout: 0.5
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true

    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.5
    linear.x.min_velocity: -0.5
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0